
-- Phase 10 Production tables

create table if not exists audit_logs (
 id bigint generated by default as identity primary key,
 action text,
 module text,
 details text,
 created_at timestamp default now()
);

create table if not exists user_profiles (
 id uuid primary key,
 role text default 'staff',
 shop_id bigint
);
